### ISSUE TITLE
recv function blocked when handle process_server_headers. 

### ISSUE THREAD

**Issue by hanbaga** [tinyproxy/tinyproxy#9]
```
(gdb) bt
#0  0x00000037b46e96b2 in recv () from /lib64/libc.so.6
#1  0x00000000004060c7 in recv (fd=7, whole_buffer=0x7fff12796830) at /usr/include/bits/socket2.h:45
#2  readline (fd=7, whole_buffer=0x7fff12796830) at network.c:167
#3  0x000000000040774d in process_server_headers (fd=<value optimized out>) at reqs.c:966
#4  handle_connection (fd=<value optimized out>) at reqs.c:1498
#5  0x0000000000402e05 in child_main (ptr=0x7f65b2a9f0fc) at child.c:237
#6  child_make (ptr=0x7f65b2a9f0fc) at child.c:296
#7  0x0000000000402fe2 in child_main_loop () at child.c:414
#8  0x0000000000409219 in main (argc=<value optimized out>, argv=0x7fff127969d8) at main.c:462
```
I think need set idle_timeout as socket receive time-out also. @obnoxxx

**Comment by obnoxxx** [comment]
Thanks for the report.
Can you describe in a little more detail how this is triggered?
